[supervisord]
nodaemon=true
logfile=/dev/stdout
loglevel=info

[program:bgutil-server]
command=node /pot-server/build/main.js
directory=/pot-server
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PORT=4416

[program:telegram-bot]
command=python bot.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=TELEGRAM_BOT_TOKEN=%(ENV_TELEGRAM_BOT_TOKEN)s
